### ISSUE TITLE
Rapid successive calls to onShake callback on Android

### ISSUE THREAD

**Issue by dhikshith12** [tpucci/shake_gesture#4]
After trying to replace our [existing package](https://pub.dev/packages/shake_detector) with this package,

I've ran into these issues on Android,  
1.  android build fails when trying to customise shake force threshold.
2.  sometimes the onShake callback is getting called rapidly 10, 100's of times in a second.
3.  emulator `cmd + m` simulation for shake gesture is not working after following Readme steps to do so.

Thats said this package is working perfectly fine on iOS since it's using existing apple sdk motionShake.

I have reverted back to the old package afterwards, i'll try to add the screenshots of the issues.

**Comment by tpucci** [comment]
Sorry to see that you have those issue.
The first one is fixed in `1.0.3`. Indeed, the metadatas were already defined in the module.

Emulator simulation shake gesture only work on a detached emulator window. If you have your emulator inside a toolbox in Android Studio, it won't work. `CMD+M` acts as a press on a media button, a button that disappeared long ago.

The snippet in the readme redirects call to that button to the skake module. Just like React Native do.

For the repeated calls, do you have a reproducible demo ? I can't simulate that behavior on my side

**Comment by tpucci** [comment]
I will reopen this issue if I can reproduce it ✅
